import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.css';
import 'reactfine-ui/dist/index.css';

const geistSans = Montserrat({
	variable: '--font-geist-sans',
	subsets: ['latin'],
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Reactfine-ui',
	icons: {
		icon: '/logo.png',
	},
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${geistSans.variable} antialiased`}>{children}</body>
		</html>
	);
}
